name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

env:
  # Indicates the CMake build directory where project files and binaries are being produced.
  CMAKE_BUILD_DIR: ${{ github.workspace }}/build/
  VGFX_SAMPLES: ON

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: lukka/get-cmake@latest

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Generate project files
      run: cmake -B "${{ env.CMAKE_BUILD_DIR }}" -S "." -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX="SDK"
     
    - name: Build
      run: cmake --build "${{ env.CMAKE_BUILD_DIR }}" --target install --config Release

    - uses: actions/upload-artifact@v2
      with:
        name: 'Windows SDK'
        path: ${{ github.workspace }}/SDK

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout    
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev

    - uses: lukka/get-cmake@latest

    # Run CMake to generate Ninja project files
    - name: Generate project files
      run: cmake -B "${{ env.CMAKE_BUILD_DIR }}" -S "." -GNinja -DCMAKE_INSTALL_PREFIX="SDK"

    # Build the whole project with Ninja (which is spawn by CMake).          
    - name: Build
      run: cmake --build "${{ env.CMAKE_BUILD_DIR }}" --target install --config Release

    - uses: actions/upload-artifact@v2
      with:
        name: 'Linux SDK'
        path: ${{ github.workspace }}/SDK      